source 'https://cdn.cocoapods.org/'

use_frameworks!

target 'Puyopuyo_Example' do
  pod 'Puyopuyo', :path => '../'
  pod 'TangramKit'
  pod 'RxSwift'

  target 'Puyopuyo_Tests' do
    inherit! :search_paths

    
  end
end
